name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: yarn install
        run: yarn install --frozen-lockfile

      - name: Run lint
        run: yarn lint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: yarn install
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test
